*&---------------------------------------------------------------------*
*& Include          ZTGPPEC0006TOP
*&---------------------------------------------------------------------*
TABLES: SSCRFIELDS,ZTPPEC0015,ZTPPEC0016,ZTPPMO0011,ZTPPEC0005,ZTPPEC0017,ZTPPEC0025.
SELECTION-SCREEN FUNCTION KEY 1.
SELECTION-SCREEN FUNCTION KEY 2.
*SELECTION-SCREEN FUNCTION KEY 3.

SELECTION-SCREEN BEGIN OF BLOCK BK1 WITH FRAME TITLE TEXT-001.
  PARAMETERS:
    P_R1 RADIOBUTTON GROUP GRP1 DEFAULT 'X' USER-COMMAND CL1, "生管維護庫存
    P_R2 RADIOBUTTON GROUP GRP1, "生管維護預採帳
    P_R3 RADIOBUTTON GROUP GRP1, "業務回復作業
    P_R4 RADIOBUTTON GROUP GRP1, "采購單價回復作業
    P_R5 RADIOBUTTON GROUP GRP1, "工程回復作業
    P_R6 RADIOBUTTON GROUP GRP1, "上傳批量報庫存
    P_R7 RADIOBUTTON GROUP GRP1. "上傳批量報庫存單價
SELECTION-SCREEN END OF BLOCK BK1.
SELECTION-SCREEN BEGIN OF BLOCK BK2 WITH FRAME TITLE TEXT-002.
  PARAMETERS P_WERKS LIKE MARC-WERKS OBLIGATORY DEFAULT '1120' MODIF ID AA.
  PARAMETERS P_ZID LIKE ZTPPMO0011-ZID MODIF ID AA.
  PARAMETERS P_ZMCRID LIKE ZTPPEC0005-ZMCRID MODIF ID AA.
  PARAMETERS P_ZVERSN LIKE ZTPPEC0017-ZVERSN DEFAULT '00' MODIF ID AA. "版次
*  SELECT-OPTIONS S_ZID FOR ZTPPMO0011-ZID.
*  SELECT-OPTIONS S_ZMCRID FOR ZTPPEC0005-ZMCRID.
  PARAMETERS P_SHOW TYPE CHAR1 NO-DISPLAY. "只顯示
  PARAMETERS P_SHOW2 TYPE CHAR1 NO-DISPLAY. "只顯示
  PARAMETERS P_PATH LIKE RLGRAP-FILENAME MODIF ID BB.
SELECTION-SCREEN END OF BLOCK BK2.

DATA OK_CODE TYPE SY-UCOMM.
DATA SAVE_OK TYPE SY-UCOMM.
DATA GV_ANSWER TYPE CHAR1.
DATA GV_MSGTEXT TYPE CHAR100.

DATA:
  BEGIN OF GT_ALV OCCURS 0,
    ZID      LIKE ZTPPEC0015-ZID,
    WERKS    LIKE ZTPPEC0015-WERKS,
    ZMCNTYPE LIKE ZTPPEC0015-ZMCNTYPE,
  END OF GT_ALV.

*100屏幕
DATA GT_ZMCNTYPE LIKE TABLE OF DD07V WITH HEADER LINE.
DATA GT_ZSTOCK_STAT LIKE TABLE OF DD07V WITH HEADER LINE.
DATA GT_ZTPPEC0025 LIKE TABLE OF ZTPPEC0025 WITH HEADER LINE.

DATA:
  BEGIN OF GS_SCR0100.
    INCLUDE STRUCTURE ZTPPEC0015.
DATA:
    VTWEG_T    TYPE CHAR20, "單據客戶別
    ZMCNTYPE_T TYPE CHAR10,
    OPTYPE     TYPE CHAR1, "C創建U修改，
  END OF  GS_SCR0100.
DATA GS_ZTPPMO0011 LIKE ZTPPMO0011.
DATA GS_ZTPPEC0005 LIKE ZTPPEC0005.
DATA GS_ZTPPEC0017 LIKE ZTPPEC0017.
DATA:
  BEGIN OF GS_TABKUC0100.
    INCLUDE STRUCTURE ZTPPEC0016.
DATA:
    SEL       TYPE CHAR1,
    MAKTX     LIKE MAKT-MAKTX,
    MEINS     LIKE MARA-MEINS,
    MSTAE     LIKE MARA-MSTAE,
    BESKZ     LIKE MARC-BESKZ, "外購
    SOBSL     LIKE MARC-SOBSL, "是否外包
    QUANTITY  LIKE ZTPPRP0019-QUANTITY, "工廠庫存數（理論存量）
    ISDJCZ    TYPE CHAR1, "單價是否存在
*    KHB       LIKE ZTSD0020-VTWEG, "客戶別
    Z_PRC     LIKE ZTPPEC0025-Z_PRC, "生管权限
    Z_SALS    LIKE ZTPPEC0025-Z_SALS, "業務权限
    Z_PUR     LIKE ZTPPEC0025-Z_PUR, "採購权限
    Z_PRC_STC LIKE ZTPPEC0025-Z_PRC_STC, "待列权限
    MCRSTAT   LIKE ZTPPEC0017-MCRSTAT, "1初核/2復核
  END OF GS_TABKUC0100,
  GT_TABKUC0100 LIKE TABLE OF GS_TABKUC0100.

*&SPWIZARD: DECLARATION OF TABLECONTROL 'GTB_TABKUC0100' ITSELF
CONTROLS: GTB_TABKUC0100 TYPE TABLEVIEW USING SCREEN 0100.

*200屏幕

DATA:
  BEGIN OF GS_SCR0200.
    INCLUDE STRUCTURE ZTPPEC0015.
DATA:
    ZMCNTYPE_T TYPE CHAR10,
  END OF  GS_SCR0200.
DATA:
  BEGIN OF GS_TABKUC0200.
    INCLUDE STRUCTURE ZTPPEC0016.
DATA:
    SEL      TYPE CHAR1,
    MAKTX    LIKE MAKT-MAKTX,
    MEINS    LIKE MARA-MEINS,
    MSTAE    LIKE MARA-MSTAE,
    QUANTITY LIKE ZTPPRP0019-QUANTITY, "工廠庫存數（理論存量）
  END OF GS_TABKUC0200,
  GT_TABKUC0200 LIKE TABLE OF GS_TABKUC0200.

*&SPWIZARD: DECLARATION OF TABLECONTROL 'GTB_TABKUC0200' ITSELF
CONTROLS: GTB_TABKUC0200 TYPE TABLEVIEW USING SCREEN 0200.


DATA:
  BEGIN OF GS_EXCEL_R1,
    ZID           LIKE ZTPPEC0015-ZID,           "單據號碼
    ZVERSN        LIKE ZTPPEC0015-ZVERSN,        "版次
    WERKS         LIKE ZTPPEC0015-WERKS,         "工廠
    MATNR         LIKE ZTPPEC0016-MATNR,         "料號
    ZDECL_QTY     LIKE ZTPPEC0016-ZDECL_QTY,     "報庫存數量
    ZSTOCK_STAT   LIKE ZTPPEC0016-ZSTOCK_STAT,   "報庫處理方式
    ZPMREMARK     LIKE ZTPPEC0016-ZPMREMARK,     "生管備注
    ISOK          LIKE ZTPPEC0016-ISOK,          "是否處理OK，
    ZREPL_INV     LIKE ZTPPEC0016-ZREPL_INV,     "是否補報庫存
    VTWEG_T       TYPE CHAR20, "單據客戶別
    ZMCNTYPE_T    TYPE CHAR10, "單據類型描述

    SEL           TYPE CHAR1,  "選擇
    MSG_TYPE      TYPE CHAR1,  "消息類型
    MSG_TEXT      TYPE CHAR50, "消息文本
    OPTYPE        TYPE CHAR1,  "C創建U修改，

*ZTPPEC0015表字段
    ZYWFZR        LIKE ZTPPEC0015-ZYWFZR,        "業務負責人
    ZSGZT         LIKE ZTPPEC0015-ZSGZT,         "生管狀態
    WL2_CUST      LIKE ZTPPEC0015-WL2_CUST,      "客戶別
    ZMCNTYPE      LIKE ZTPPEC0015-ZMCNTYPE,      "單據類別（指定PO或MCR變更）
    ERDAT         LIKE ZTPPEC0015-ERDAT,
    ERZET         LIKE ZTPPEC0015-ERZET,
    ERNAM         LIKE ZTPPEC0015-ERNAM,
    AEDAT         LIKE ZTPPEC0015-AEDAT,
    AEZET         LIKE ZTPPEC0015-AEZET,
    AENAM         LIKE ZTPPEC0015-AENAM,
    TCODE         LIKE ZTPPEC0015-TCODE,
    ZDECL_QTY_O   LIKE ZTPPEC0016-ZDECL_QTY,     "報庫存數量
    ZSTOCK_STAT_O LIKE ZTPPEC0016-ZSTOCK_STAT,   "報庫處理方式
    ZPMREMARK_O   LIKE ZTPPEC0016-ZPMREMARK,     "生管備注
    ISOK_O        LIKE ZTPPEC0016-ISOK,          "是否處理OK，
    ZREPL_INV_O   LIKE ZTPPEC0016-ZREPL_INV,     "是否補報庫存

*ZTPPEC0016表字段
    ZSEQ          LIKE ZTPPEC0016-ZSEQ,
    ZTOT_STOCK    LIKE ZTPPEC0016-ZTOT_STOCK,
    ZSTOCK_STAT2  LIKE ZTPPEC0016-ZSTOCK_STAT2,
    ZUPRICE       LIKE ZTPPEC0016-ZUPRICE,
    WAERS         LIKE ZTPPEC0016-WAERS,
    ZZCN          LIKE ZTPPEC0016-ZZCN,
    KUNAG         LIKE ZTPPEC0016-KUNAG,
    ZUNIT_CONS    LIKE ZTPPEC0016-ZUNIT_CONS,
    ZTF_PREPO     LIKE ZTPPEC0016-ZTF_PREPO,
    ZPM_AENAM     LIKE ZTPPEC0016-ZPM_AENAM,
    ZPM_AEDAT     LIKE ZTPPEC0016-ZPM_AEDAT,
    ZREP_AENAM    LIKE ZTPPEC0016-ZREP_AENAM,
    ZREP_AEDAT    LIKE ZTPPEC0016-ZREP_AEDAT,
    ZSA_REP       LIKE ZTPPEC0016-ZSA_REP,
    ZSA_AENAM     LIKE ZTPPEC0016-ZSA_AENAM,
    ZSA_AEDAT     LIKE ZTPPEC0016-ZSA_AEDAT,
    ZPU_AENAM     LIKE ZTPPEC0016-ZPU_AENAM,
    ZPU_AEDAT     LIKE ZTPPEC0016-ZPU_AEDAT,
    ZDNNO         LIKE ZTPPEC0016-ZDNNO,
    ERDAT2        LIKE ZTPPEC0016-ERDAT,
    ERZET2        LIKE ZTPPEC0016-ERZET,
    ERNAM2        LIKE ZTPPEC0016-ERNAM,
    AEDAT2        LIKE ZTPPEC0016-AEDAT,
    AEZET2        LIKE ZTPPEC0016-AEZET,
    AENAM2        LIKE ZTPPEC0016-AENAM,
    TCODE2        LIKE ZTPPEC0016-TCODE,

    MAKTX         LIKE MAKT-MAKTX,
    MEINS         LIKE MARA-MEINS,
    MSTAE         LIKE MARA-MSTAE,
    QUANTITY      LIKE ZTPPRP0019-QUANTITY, "工廠庫存數（理論存量）
    ISDJCZ        TYPE CHAR1, "單價是否存在
    KHB           LIKE ZTSD0020-VTWEG, "客戶別
    Z_PRC         LIKE ZTPPEC0025-Z_PRC, "生管权限
    Z_SALS        LIKE ZTPPEC0025-Z_SALS, "業務权限
    Z_PUR         LIKE ZTPPEC0025-Z_PUR, "採購权限
    Z_PRC_STC     LIKE ZTPPEC0025-Z_PRC_STC, "待列权限
  END OF GS_EXCEL_R1,
  GT_EXCEL_R1 LIKE TABLE OF GS_EXCEL_R1.


DATA:
  BEGIN OF GS_EXCEL_R2,
    ZID          LIKE ZTPPEC0015-ZID,           "單據號碼
    ZVERSN       LIKE ZTPPEC0015-ZVERSN,        "版次
    WERKS        LIKE ZTPPEC0015-WERKS,         "工廠
    MATNR        LIKE ZTPPEC0016-MATNR,         "料號
    ZUPRICE      LIKE ZTPPEC0016-ZUPRICE,       "單價
    WAERS        LIKE ZTPPEC0016-WAERS,         "幣別
    VTWEG_T      TYPE CHAR20, "單據客戶別
    ZMCNTYPE_T   TYPE CHAR10, "單據類型描述

    SEL          TYPE CHAR1,  "選擇
    MSG_TYPE     TYPE CHAR1,  "消息類型
    MSG_TEXT     TYPE CHAR50, "消息文本
    OPTYPE       TYPE CHAR1,  "C創建U修改，


*ZTPPEC0015表字段
    ZYWFZR       LIKE ZTPPEC0015-ZYWFZR,        "業務負責人
    ZSGZT        LIKE ZTPPEC0015-ZSGZT,         "生管狀態
    WL2_CUST     LIKE ZTPPEC0015-WL2_CUST,      "客戶別
    ZMCNTYPE     LIKE ZTPPEC0015-ZMCNTYPE,      "單據類別（指定PO或MCR變更）
    ERDAT        LIKE ZTPPEC0015-ERDAT,
    ERZET        LIKE ZTPPEC0015-ERZET,
    ERNAM        LIKE ZTPPEC0015-ERNAM,
    AEDAT        LIKE ZTPPEC0015-AEDAT,
    AEZET        LIKE ZTPPEC0015-AEZET,
    AENAM        LIKE ZTPPEC0015-AENAM,
    TCODE        LIKE ZTPPEC0015-TCODE,
*ZTPPEC0016表字段
    ZDECL_QTY    LIKE ZTPPEC0016-ZDECL_QTY,     "報庫存數量
    ZSTOCK_STAT  LIKE ZTPPEC0016-ZSTOCK_STAT,   "報庫處理方式
    ZPMREMARK    LIKE ZTPPEC0016-ZPMREMARK,     "生管備注
    ISOK         LIKE ZTPPEC0016-ISOK,          "是否處理OK，
    ZREPL_INV    LIKE ZTPPEC0016-ZREPL_INV,     "是否補報庫存
    ZSEQ         LIKE ZTPPEC0016-ZSEQ,
    ZTOT_STOCK   LIKE ZTPPEC0016-ZTOT_STOCK,
    ZSTOCK_STAT2 LIKE ZTPPEC0016-ZSTOCK_STAT2,
    ZUPRICE_O    LIKE ZTPPEC0016-ZUPRICE2,
    WAERS_O      LIKE ZTPPEC0016-WAERS,
    ZZCN         LIKE ZTPPEC0016-ZZCN,
    KUNAG        LIKE ZTPPEC0016-KUNAG,
    ZUNIT_CONS   LIKE ZTPPEC0016-ZUNIT_CONS,
    ZTF_PREPO    LIKE ZTPPEC0016-ZTF_PREPO,
    ZPM_AENAM    LIKE ZTPPEC0016-ZPM_AENAM,
    ZPM_AEDAT    LIKE ZTPPEC0016-ZPM_AEDAT,
    ZREP_AENAM   LIKE ZTPPEC0016-ZREP_AENAM,
    ZREP_AEDAT   LIKE ZTPPEC0016-ZREP_AEDAT,
    ZSA_REP      LIKE ZTPPEC0016-ZSA_REP,
    ZSA_AENAM    LIKE ZTPPEC0016-ZSA_AENAM,
    ZSA_AEDAT    LIKE ZTPPEC0016-ZSA_AEDAT,
    ZPU_AENAM    LIKE ZTPPEC0016-ZPU_AENAM,
    ZPU_AEDAT    LIKE ZTPPEC0016-ZPU_AEDAT,
    ZDNNO        LIKE ZTPPEC0016-ZDNNO,
    ERDAT2       LIKE ZTPPEC0016-ERDAT,
    ERZET2       LIKE ZTPPEC0016-ERZET,
    ERNAM2       LIKE ZTPPEC0016-ERNAM,
    AEDAT2       LIKE ZTPPEC0016-AEDAT,
    AEZET2       LIKE ZTPPEC0016-AEZET,
    AENAM2       LIKE ZTPPEC0016-AENAM,
    TCODE2       LIKE ZTPPEC0016-TCODE,

    MAKTX        LIKE MAKT-MAKTX,
    MEINS        LIKE MARA-MEINS,
    MSTAE        LIKE MARA-MSTAE,
    QUANTITY     LIKE ZTPPRP0019-QUANTITY, "工廠庫存數（理論存量）
    ISDJCZ       TYPE CHAR1, "單價是否存在
    KHB          LIKE ZTSD0020-VTWEG, "客戶別
    Z_PRC        LIKE ZTPPEC0025-Z_PRC, "生管权限
    Z_SALS       LIKE ZTPPEC0025-Z_SALS, "業務权限
    Z_PUR        LIKE ZTPPEC0025-Z_PUR, "採購权限
    Z_PRC_STC    LIKE ZTPPEC0025-Z_PRC_STC, "待列权限

    DEL          TYPE CHAR1, "刪除標示
  END OF GS_EXCEL_R2,
  GT_EXCEL_R2 LIKE TABLE OF GS_EXCEL_R2.


DATA:
  LAYOUT    TYPE SLIS_LAYOUT_ALV,
  CLASS     TYPE REF TO ZALV_GUI_CUSTOM_CLASS,              "#EC NEEDED
  G_SAVE(1) TYPE C,
  G_REPID   TYPE SY-REPID,
  GT_EVENTS TYPE SLIS_T_EVENT.

DATA G_PRINT     TYPE SLIS_PRINT_ALV.
DATA GT_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV.
DATA GT_SORTINFO TYPE SLIS_T_SORTINFO_ALV.
DATA G_VARIANT   LIKE DISVARIANT.
DATA SEL_INDEX   LIKE SY-INDEX.
DATA: G_CURR_VBTYP LIKE TVAK-VBTYP.

*取價格全局變量
DATA:
  BEGIN OF GS_MATNRPRICE,
    MATNR    LIKE MARA-MATNR,
    WERKS    LIKE MARC-WERKS,
    BESKZ    LIKE MARC-BESKZ,
    SOBSL    LIKE MARC-SOBSL,
    ZUPRICE  LIKE ZTPPEC0016-ZUPRICE,
    ZUPRICE2 LIKE ZTPPEC0016-ZUPRICE2,
    WAERS    LIKE ZTPPEC0016-WAERS,
    ISDJCZ   TYPE CHAR1, "單價是否存在
  END OF GS_MATNRPRICE.
DATA: GT_MATNRPRICE LIKE TABLE OF GS_MATNRPRICE WITH HEADER LINE.