PROCESS BEFORE OUTPUT.
  MODULE STATUS_0100.
*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'GTB_TABKUC0100'
  MODULE GTB_TABKUC0100_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE GTB_TABKUC0100_CHANGE_COL_ATTR.
  LOOP AT   GT_TABKUC0100
       INTO GS_TABKUC0100
       WITH CONTROL GTB_TABKUC0100
       CURSOR GTB_TABKUC0100-CURRENT_LINE.
*&SPWIZARD:   MODULE GTB_TABKUC0100_CHANGE_FIELD_ATTR
    MODULE TABKUC0100_STATUS.
  ENDLOOP.


PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'GTB_TABKUC0100'
  LOOP AT GT_TABKUC0100.
    CHAIN.
      FIELD GS_TABKUC0100-ZSA_REP.
      FIELD GS_TABKUC0100-ZSTOCK_STAT2.
      FIELD GS_TABKUC0100-ZDNNO.
      MODULE GTB_TABKUC0100_ZSA_REP ON CHAIN-REQUEST.
    ENDCHAIN.
    CHAIN.
      FIELD GS_TABKUC0100-ZUPRICE2.
      FIELD GS_TABKUC0100-WAERS.
      MODULE GTB_TABKUC0100_ZUPRICE ON CHAIN-REQUEST.
    ENDCHAIN.
    CHAIN.
      FIELD GS_TABKUC0100-MATNR.
      MODULE GTB_TABKUC0100_MATNR ON CHAIN-REQUEST.
    ENDCHAIN.
    CHAIN.
      FIELD GS_TABKUC0100-ZZCN.
      FIELD GS_TABKUC0100-ZUNIT_CONS.
      FIELD GS_TABKUC0100-ZSTOCK_STAT.
      MODULE GTB_TABKUC0100_ZSTOCK_STAT.
    ENDCHAIN.
    CHAIN.
      FIELD GS_TABKUC0100-ZSEQ.
      FIELD GS_TABKUC0100-MATNR.
      FIELD GS_TABKUC0100-ZDECL_QTY.
*      FIELD GS_TABKUC0100-ZTOT_STOCK.
      FIELD GS_TABKUC0100-ZSTOCK_STAT.
      FIELD GS_TABKUC0100-ZSTOCK_STAT2.
      FIELD GS_TABKUC0100-ISOK.
      FIELD GS_TABKUC0100-ZPMREMARK.
      FIELD GS_TABKUC0100-ZREPL_INV.
      FIELD GS_TABKUC0100-ZUPRICE2.
      FIELD GS_TABKUC0100-WAERS.
      FIELD GS_TABKUC0100-ZZCN.
      FIELD GS_TABKUC0100-ZUNIT_CONS.
      FIELD GS_TABKUC0100-ZTF_PREPO.
      FIELD GS_TABKUC0100-KHB.
      FIELD GS_TABKUC0100-ZDNNO.
      FIELD GS_TABKUC0100-ZSA_REP.
*      MODULE CHECK_MATNR100.
      MODULE GTB_TABKUC0100_MODIFY ON CHAIN-REQUEST.
    ENDCHAIN.
    FIELD GS_TABKUC0100-SEL
      MODULE GTB_TABKUC0100_MARK ON REQUEST.
*    FIELD GS_TABKUC0100-MATNR MODULE CHECK_MATNR100.
  ENDLOOP.
*&SPWIZARD: MODULE GTB_TABKUC0100_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE GTB_TABKUC0100_CHANGE_COL_ATTR.

  MODULE USER_COMMAND_0100.

  MODULE EXIT_0100 AT EXIT-COMMAND.

PROCESS ON VALUE-REQUEST.
  FIELD GS_SCR0100-ZMCNTYPE MODULE SEARCH_HELP_ZMCNTYPE.