****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
ZTWBSD0022																																
1100																																
757																																
                40																																
%_HEADER																																
ZTWBSD0022                              1100W1100      5120200 36  0  0200120  0G ESEL_SCREEN 1100 INFO:17000032020260102153506																																
%_DESCRIPTION																																
SEL_SCREEN 1100 INFO:170000320000000000000000000099798456506																																
%_FIELDS																																
%BS01001_BLOCK_1100	C	CHAR	118	80	02	80	31	00	  1	  2		  0	  0	  0		  4	R				  0	  0	101					BLK				
%_PCZPNOI_%_APP_%-TEXT	C	CHAR	 30	80	02	80	31	00	  2	  4		  0	  0	  0		 30					  0	  0						TXT	002		                                                                                                                                                                                                                                                        X	
PCZPNOI	C	CHAR	 30	80	00	80	00	00	  2	 36		  0	  0	  0		 30					  0	  0						PAR	002	______________________________		
%_PCZDESC_%_APP_%-TEXT	C	CHAR	 30	80	02	80	31	00	  3	  4		  0	  0	  0		 30					  0	  0						TXT	003		                                                                                                                                                                                                                                                        X	
PCZDESC	C	CHAR	150	81	02	80	00	00	  3	 36		  0	  0	  0		 45					  0	  0						PAR	003	_____________________________________________		
%_17NNW0000839041_%_%_%_%_%_%_	C	CHAR	  1	00	00	00	00	00	  5	  2		  0	  0	  0		  0					  0	  0							SRI	-		
SSCRFIELDS-UCOMM	C	CHAR	 70	A0	10	00	00	00	255	  5	O	  0	  0	  0		 70					140	  0								______________________________________________________________________	                                       00	
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
																																
MODULE %_INIT_PBO.																																
																																
MODULE %_PBO_REPORT.																																
																																
MODULE %_PF_STATUS.																																
																																
MODULE %_END_OF_PBO.																																
																																
PROCESS AFTER INPUT.																																
																																
  MODULE %_BACK AT EXIT-COMMAND.																																
																																
  MODULE %_INIT_PAI.																																
																																
FIELD !PCZPNOI MODULE %_PCZPNOI .																																
																																
FIELD !PCZDESC MODULE %_PCZDESC .																																
																																
																																
CHAIN.																																
  FIELD PCZPNOI .																																
  FIELD PCZDESC .																																
    MODULE %_BLOCK_1100001.																																
ENDCHAIN.																																
																																
CHAIN.																																
  FIELD PCZPNOI .																																
  FIELD PCZDESC .																																
  MODULE %_END_OF_SCREEN.																																
  MODULE %_OK_CODE_1000.																																
ENDCHAIN.																																
