PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'GTB_TABKUC0200'
  MODULE GTB_TABKUC0200_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE GTB_TABKUC0200_CHANGE_COL_ATTR.
  LOOP AT   GT_TABKUC0200
       INTO GS_TABKUC0200
       WITH CONTROL GTB_TABKUC0200
       CURSOR GTB_TABKUC0200-CURRENT_LINE.
*&SPWIZARD:   MODULE GTB_TABKUC0200_CHANGE_FIELD_ATTR
  ENDLOOP.

  MODULE STATUS_0200.

PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'GTB_TABKUC0200'
  LOOP AT GT_TABKUC0200.
    CHAIN.
      FIELD GS_TABKUC0200-ZSEQ.
      FIELD GS_TABKUC0200-MATNR.
      FIELD GS_TABKUC0200-ZDECL_QTY.
      FIELD GS_TABKUC0200-ZTOT_STOCK.
      FIELD GS_TABKUC0200-ZSTOCK_STAT.
      FIELD GS_TABKUC0200-ZPMREMARK.
      FIELD GS_TABKUC0200-ZREPL_INV.
      FIELD GS_TABKUC0200-ZUPRICE2.
      FIELD GS_TABKUC0200-WAERS.
      FIELD GS_TABKUC0200-MAKTX.
      FIELD GS_TABKUC0200-MEINS.
      MODULE GTB_TABKUC0200_MODIFY ON CHAIN-REQUEST.
    endchain.
    FIELD GS_TABKUC0200-SEL
      MODULE GTB_TABKUC0200_MARK ON REQUEST.
  ENDLOOP.
*&SPWIZARD: MODULE GTB_TABKUC0200_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE GTB_TABKUC0200_CHANGE_COL_ATTR.

  MODULE USER_COMMAND_0200.

  MODULE EXIT_0200 AT EXIT-COMMAND.