PROCESS BEFORE OUTPUT.

MODULE %_INIT_PBO.

MODULE %_PBO_REPORT.

MODULE %_PF_STATUS.

MODULE %_END_OF_PBO.

PROCESS AFTER INPUT.

  MODULE %_BACK AT EXIT-COMMAND.

  MODULE %_INIT_PAI.

CHAIN.
  FIELD P_R1    .
  FIELD P_R2    .
  FIELD P_R3    .
  FIELD P_R4    .
  FIELD P_R5    .
  FIELD P_R6    .
  FIELD P_R7    .
    MODULE %_RADIOBUTTON_GROUP_GRP1                          .
ENDCHAIN.


CHAIN.
  FIELD P_R1    .
  FIELD P_R2    .
  FIELD P_R3    .
  FIELD P_R4    .
  FIELD P_R5    .
  FIELD P_R6    .
  FIELD P_R7    .
    MODULE %_BLOCK_1000002.
ENDCHAIN.

FIELD !P_WERKS MODULE %_P_WERKS .

FIELD !P_ZID MODULE %_P_ZID .

FIELD !P_ZMCRID MODULE %_P_ZMCRID .

FIELD !P_ZVERSN MODULE %_P_ZVERSN .

FIELD !P_PATH MODULE %_P_PATH .


CHAIN.
  FIELD P_WERKS .
  FIELD P_ZID .
  FIELD P_ZMCRID .
  FIELD P_ZVERSN .
  FIELD P_PATH .
    MODULE %_BLOCK_1000011.
ENDCHAIN.

CHAIN.
  FIELD P_R1    .
  FIELD P_R2    .
  FIELD P_R3    .
  FIELD P_R4    .
  FIELD P_R5    .
  FIELD P_R6    .
  FIELD P_R7    .
  FIELD P_WERKS .
  FIELD P_ZID .
  FIELD P_ZMCRID .
  FIELD P_ZVERSN .
  FIELD P_PATH .
  MODULE %_END_OF_SCREEN.
  MODULE %_OK_CODE_1000.
ENDCHAIN.

PROCESS ON VALUE-REQUEST.
  FIELD P_ZID MODULE %_P_ZID_VAL .
  FIELD P_ZMCRID MODULE %_P_ZMCRID_VAL .
  FIELD P_PATH MODULE %_P_PATH_VAL .