*&---------------------------------------------------------------------*
*& Report ZTGPPEC0006
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZTGPPEC0006.

INCLUDE ZTGPPEC0006TOP.
INCLUDE ZTGPPEC0006PBO.
INCLUDE ZTGPPEC0006PAI.
INCLUDE ZTGPPEC0006CLS.
INCLUDE ZTGPPEC0006FRM.

INITIALIZATION.
  PERFORM INITIAL.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR P_ZID.
  PERFORM SEARCHHELP_ZID.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR P_ZMCRID.
  PERFORM SEARCHHELP_ZMCRID.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR P_PATH.
  PERFORM SET_FILEPATH.

AT SELECTION-SCREEN.
  CASE SSCRFIELDS-UCOMM.
    WHEN 'FC01' OR 'FC02'.
      PERFORM FRM_DOWNEXCEL.
    WHEN 'FC03'.
      PERFORM FRM_SETEMAIL.
  ENDCASE.

AT SELECTION-SCREEN OUTPUT.
  IF P_R6 = 'X' OR P_R7 = 'X'.
    LOOP AT SCREEN.
      IF SCREEN-GROUP1 = 'AA'.
        SCREEN-ACTIVE = '0'.
      ENDIF.
      MODIFY SCREEN.
    ENDLOOP.
  ELSE.
    LOOP AT SCREEN.
      IF SCREEN-GROUP1 = 'BB'.
        SCREEN-ACTIVE = '0'.
      ENDIF.
      MODIFY SCREEN.
    ENDLOOP.
  ENDIF.

START-OF-SELECTION.
  IF P_R6 = 'X'.
  ELSEIF P_R7 = 'X'.
  ELSEIF P_R1 = 'X' OR P_R2 = 'X'.
    AUTHORITY-CHECK OBJECT 'ZQXPEC006'
     ID 'ZQXPEC006' FIELD '10'.
    IF SY-SUBRC <> 0.
      MESSAGE '沒有生管權限' TYPE 'S' DISPLAY LIKE 'E'.
      RETURN.
    ENDIF.
  ELSEIF P_R3 = 'X'.
    AUTHORITY-CHECK OBJECT 'ZQXPEC006'
     ID 'ZQXPEC006' FIELD '20'.
    IF SY-SUBRC <> 0.
      MESSAGE '沒有業務權限' TYPE 'S' DISPLAY LIKE 'E'.
      RETURN.
    ENDIF.
  ELSEIF P_R4 = 'X'.
    AUTHORITY-CHECK OBJECT 'ZQXPEC006'
     ID 'ZQXPEC006' FIELD '30'.
    IF SY-SUBRC <> 0.
      MESSAGE '沒有采購權限' TYPE 'S' DISPLAY LIKE 'E'.
      RETURN.
    ENDIF.
  ELSEIF P_R5 = 'X'.
    AUTHORITY-CHECK OBJECT 'ZQXPEC006'
     ID 'ZQXPEC006' FIELD '40'.
    IF SY-SUBRC <> 0.
      MESSAGE '沒有工程權限' TYPE 'S' DISPLAY LIKE 'E'.
      RETURN.
    ENDIF.
  ENDIF.

  IF P_R6 = 'X'. "報庫存上傳
    PERFORM UPLOAD_R6.
    PERFORM SHOW_ALV.
  ELSEIF P_R7 = 'X'. "報庫存單價上傳
    PERFORM UPLOAD_R7.
    PERFORM SHOW_ALV.
  ELSE.
    IF P_ZID = '' AND P_ZMCRID = ''.
      MESSAGE 'MCR號碼和指定PO號碼不能都為空！' TYPE 'S' DISPLAY LIKE 'E'.
      RETURN.
    ELSEIF P_ZID <> '' AND P_ZMCRID <> ''.
      MESSAGE 'MCR號碼和指定PO號碼只能填一個！' TYPE 'S' DISPLAY LIKE 'E'.
      RETURN.
    ENDIF.
    PERFORM GET_DATA.
  ENDIF.